version: '2'
services:
  web:
    build: ./app
    ports:
     - "5000:5000"
    volumes:
     - ./app:/usr/src/app
    depends_on:
     - redis
     - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  redis:
    image: redis
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
